version: '3.8'

services:
  jupyterhub:
    build: .
    image: jupyter 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./data:/srv/jupyterhub/data
       - ./user_notebooks:/home  
    ports:
      - "9020:8000"
    networks:
      - jupyterhub

networks:
  jupyterhub:
    name: jupyterhub
